In [ ]:
import torch
import torch.nn as nn
import numpy as np

In [ ]:
a = torch.Tensor([1, 2, 3, 4, 5,6])
b = torch.Tensor([[1,2,3],[4,5,6],[7,8,9]])

In [ ]:
print(a.shape)

torch.Size([6])


In [ ]:
print(b.shape)

torch.Size([3, 3])


In [ ]:
a.reshape(2,3)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [ ]:
c = b.reshape(1,9)

In [ ]:
c.reshape(3,3)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [ ]:
c = torch.Tensor([[0.7,0.5,0],[1,1.5,0.55],[0.3,1,0]])

In [ ]:
_, predicted = torch.max(c.data, 1)

In [ ]:
predicted

tensor([0, 1, 1])

In [ ]:
_

tensor([0, 1, 1])

In [ ]:
d = c > 0.5

In [ ]:
d = d.type(torch.float)

In [ ]:
d

tensor([[1., 0., 0.],
        [1., 1., 1.],
        [0., 1., 0.]])

In [ ]:
e = torch.Tensor([[1,0,1],[1,1,0],[0,1,0]])

In [ ]:
e

tensor([[1., 0., 1.],
        [1., 1., 0.],
        [0., 1., 0.]])

In [ ]:
e.shape

torch.Size([3, 3])

In [ ]:
(e == d).sum().item()

7

In [ ]:
torch.unique(d)

tensor([0., 1.])

In [ ]:
def compute_iou(pred, target):
    p = pred.numpy()
    t = target.numpy()
    I =   len(np.argwhere(np.logical_and(p==1,t==1)))/len(np.argwhere(np.logical_or(p==1,t==1)))
    print(I)
    U =   len(np.argwhere(np.logical_and(p==0,t==0)))/len(np.argwhere(np.logical_or(p==0,t==0)))
    print(U)
    mean_iou = (I+U)/2
    return mean_iou

In [ ]:
compute_iou(d,e)

0.6666666666666666
0.6


0.6333333333333333

In [ ]:
import numpy as geek 
  
# input array 
in_arr = geek.arange(8).reshape(4, 2) 
out_arr = geek.arange(8).reshape(4, 2) 
print ("Input array : ", in_arr)  
  
out_arr1 = np.argwhere(np.logical_and(in_arr>4,out_arr>3))
print ("Output indices greater than 4: \n", out_arr1)
print(len(out_arr1))

Input array :  [[0 1]
 [2 3]
 [4 5]
 [6 7]]
Output indices greater than 4: 
 [[2 1]
 [3 0]
 [3 1]]
3


In [ ]:
import torchvision
from torchvision.models.detection.faster_rcnn import FastRCNNPredictor

model = torchvision.models.detection.fasterrcnn_resnet50_fpn(pretrained=False)

Downloading: "https://download.pytorch.org/models/resnet50-19c8e357.pth" to /root/.cache/torch/checkpoints/resnet50-19c8e357.pth


In [ ]:
import torch
#from grcn import * 
#model.backbone.out_channels = 18
#model.transform = GeneralizedRCNNTransform()
images, boxes = torch.rand(4, 3, 600, 1200), torch.rand(4, 11, 4)

In [ ]:
import torch.nn as nn
import torch.nn.functional as F

#model.backbone.body.conv1 = nn.Conv2d(6, 64, kernel_size=7, stride=2, padding=3, bias=False)

In [ ]:
#model.backbone.out_channels = 18
#model.backbone

In [ ]:
model

FasterRCNN(
  (transform): GeneralizedRCNNTransform()
  (backbone): BackboneWithFPN(
    (body): IntermediateLayerGetter(
      (conv1): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
      (bn1): FrozenBatchNorm2d()
      (relu): ReLU(inplace=True)
      (maxpool): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
      (layer1): Sequential(
        (0): Bottleneck(
          (conv1): Conv2d(64, 64, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (bn1): FrozenBatchNorm2d()
          (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
          (bn2): FrozenBatchNorm2d()
          (conv3): Conv2d(64, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (bn3): FrozenBatchNorm2d()
          (relu): ReLU(inplace=True)
          (downsample): Sequential(
            (0): Conv2d(64, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
            (1): FrozenBatchNorm2d()
          )
  

In [ ]:
labels = torch.randint(1, 91, (4, 11))

In [ ]:
images = list(image for image in images)

In [ ]:
images[0].shape

torch.Size([3, 600, 1200])

In [ ]:
targets = []

In [ ]:
for i in range(len(images)):
    d = {}
    d['boxes'] = boxes[i]
    d['labels'] = labels[i]
    targets.append(d)

output = model(images, targets)
print(output)

KeyboardInterrupt: ignored

In [ ]:
model.eval()

In [ ]:
x = [torch.rand(3, 300, 400), torch.rand(3, 500, 400)]

In [ ]:
predictions = model(x)

In [ ]:
predictions[0]

In [ ]:
bb = torch.Tensor([[ -8.9597283713,  -8.9240475189, -19.3947433707, -19.3590625184],
        [ -1.8503781014,  -4.6871082614,  -1.9819539259,  -4.8186840858]])
    

bb[0]

In [ ]:
bbd = torch.zeros(1,4)

In [ ]:
ymin = torch.min(bb[0])
print(ymin)
bbd[0][1] = ymin

In [ ]:
ymax = torch.max(bb[0])
print(ymax)
bbd[0][3] = ymax

In [ ]:
xmin = torch.min(bb[1])
bbd[0][0] = xmin
print(xmin)

In [ ]:
xmax = torch.max(bb[1])
print(xmax)
bbd[0][2] = xmax

In [ ]:
bbd

In [ ]:
'''

If x_min = 0, it remains 0.
 If x_min > 0, then x_min = 462 + (x_min/40)*462
If x_min < 0, then x_min = 462 - (|x_min|/40)*462
Do the same for x_max also.
For the y values, do(separately for y_min and y_max) :
If y = 0, it remains 0,
If y > 0, y = 256 + (y/40)*256
If y < 0, y = 256 - (|y|/40)*256
'''

In [ ]:
if bbd[0][0] > 0:
  bbd[0][0] = 462 + ((bbd[0][0])/40)*462
elif bbd[0][0] < 0:
  bbd[0][0] = 462 - (((abs(bbd[0][0]))/40)*462)
if bbd[0][2] > 0:
  bbd[0][2] = 462 + ((bbd[0][2])/40)*462
elif bbd[0][2] < 0:
  bbd[0][2] = 462 - ((abs(bbd[0][2])/40)*462)

In [ ]:
if bbd[0][1] > 0:
  bbd[0][1] = 256 + (bbd[0][1]/40)*256
elif bbd[0][1] < 0:
  bbd[0][1] = 256 - ((abs(bbd[0][1]))/40)*256
if bbd[0][3] > 0:
  bbd[0][3] = 256 + (bbd[0][3]/40)*256
elif bbd[0][3] < 0:
  bbd[0][3] = 256 - ((abs(bbd[0][3]))/40)*256

In [ ]:
torch.set_printoptions(precision=10)

In [ ]:
bbd

In [ ]:
import torch
import torch.nn.functional as F

a = torch.arange(1, 5).view(1, 1, 2, 2).float()
print(a)
a = F.interpolate(a, size=[8,8], mode='bilinear', align_corners=False)
print(a)

tensor([[[[1., 2.],
          [3., 4.]]]])
tensor([[[[1.0000, 1.0000, 1.1250, 1.3750, 1.6250, 1.8750, 2.0000, 2.0000],
          [1.0000, 1.0000, 1.1250, 1.3750, 1.6250, 1.8750, 2.0000, 2.0000],
          [1.2500, 1.2500, 1.3750, 1.6250, 1.8750, 2.1250, 2.2500, 2.2500],
          [1.7500, 1.7500, 1.8750, 2.1250, 2.3750, 2.6250, 2.7500, 2.7500],
          [2.2500, 2.2500, 2.3750, 2.6250, 2.8750, 3.1250, 3.2500, 3.2500],
          [2.7500, 2.7500, 2.8750, 3.1250, 3.3750, 3.6250, 3.7500, 3.7500],
          [3.0000, 3.0000, 3.1250, 3.3750, 3.6250, 3.8750, 4.0000, 4.0000],
          [3.0000, 3.0000, 3.1250, 3.3750, 3.6250, 3.8750, 4.0000, 4.0000]]]])


In [ ]:
bb1 = [torch.Tensor([ -8.9597283713,  -8.9240475189, -19.3947433707, -19.3590625184]),
       torch.Tensor( [ -1.8503781014,  -4.6871082614,  -1.9819539259,  -4.8186840858])]

In [ ]:
l = torch.stack(bb1)
print(l)

In [ ]:
t = torch.zeros([2, 3, 512, 918], dtype=torch.int32)

In [ ]:
t

In [ ]:
m = nn.Upsample(size = (2, 3, 800, 800))

In [ ]:
#m(t)

In [ ]:
t = torch.zeros(1, dtype=torch.int64)
t[0]  = 5

In [ ]:
t

tensor([5])

In [ ]:
t.dtype

torch.int64

In [ ]:
t.type()

'torch.LongTensor'